[package]
name = "coral-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
clap_complete = "4.5.1"
colored = "2.1.0"
dirs-next = "2.0.0"
ecies = { version = "0.2.6", default-features = false, features = ["pure"] }
ethers = "2.0.13"
hex = "0.4.3"
lazy_static = "1.4.0"
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
shellexpand = { version = "3.1.0", features = ["full"] }
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.2", features = [ "cors", "trace" ] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "std", "env-filter" ] }

# Puffer dependencies

coral-lib = { path = "../coral-lib" }
puffersecuresigner = { git ="https://github.com/PufferFinance/secure-signer.git" }
