[package]
name = "coral-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.2"
chrono = "0.4.31"
clap = { version = "4.4.11", features = ["derive"] }
clap_complete = "4.4.4"
colored = "2.1.0"
dirs-next = "2.0.0"
ecies = { version = "0.2.6", default-features = false, features = ["pure"] }
ethers = "2.0.11"
flexi_logger = "0.27.3"
lazy_static = "1.4.0"
rand_core = "0.6.4"
reth = "0.1.0"
reqwest = { version = "0.11.23", features = ["json"] }
rpassword = "7.3.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
shellexpand = { version = "3.1.0", features = ["full"] }
tokio = { version = "1.35.1", features = ["full"] }
toml = "0.8.8"
tower-http = { version = "0.5.0", features = [ "cors", "trace" ] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "std", "env-filter" ] }

# Puffer dependencies

coral-lib = { path = "../coral-lib" }
puffersecuresigner = { git ="https://github.com/PufferFinance/secure-signer.git" }
