name: Check

on:
  pull_request:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Check all tests
        run: cargo test
      - name: Clippy with features
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Check format
        run: cargo fmt --verbose --all -- --check
      - name: Install llvm-cov tool for cargo
        run: cargo +stable install cargo-llvm-cov --locked
      - name: Code coverage
        run: cargo llvm-cov
