name: Check

on:
  pull_request:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_POOL }}
      - name: Check all tests
        run: cargo test
      - name: Clippy with features
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Add nightly toolchain for rustfmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Check format
        run: cargo +nightly fmt --verbose --all -- --check
      - name: Install llvm-cov tool for cargo
        run: cargo +stable install cargo-llvm-cov --locked
      - name: Code coverage
        run: cargo llvm-cov
