name: Manual Release for Rust Project Workspace

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build in release mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      # - name: Run Tests
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --all

  package-and-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Download target directory
        uses: actions/download-artifact@v2
        with:
          name: target-directory
          path: target
      - name: List built binaries
        run: ls target/release
      - name: Package Binaries
        run: |
          mkdir -p release_artifacts  && \
          tar -czvf release_artifacts/coral-cli_${{ github.event.inputs.version }}.tar.gz -C target/release coral-cli
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release_artifacts
          path: release_artifacts/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
      - name: Upload Release Asset for coral-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_artifacts/coral-cli_${{ github.event.inputs.version }}.tar.gz
          asset_name: coral-cli_${{ github.event.inputs.version }}.tar.gz
          asset_content_type: application/gzip
